event/urls.py
from django.urls import path
from .views import (
    PrivateEventListView, 
    PrivateEventCreateView, 
    PrivateEventInviteView, 
    PrivateEventDetailView,
    MethodOfPaymentView,
    )


app_name = "events"
urlpatterns = [
    path("", PrivateEventListView.as_view(), name="private_event_list"),
    path("new/", PrivateEventCreateView.as_view(), name="private_event_add"),
    path("<int:pk>/invite/", PrivateEventInviteView.as_view(), name="invite_private_event"),
    path("<int:pk>/", PrivateEventDetailView.as_view(), name="private_event_detail"),
    path("payment/", MethodOfPaymentView.as_view(), name="method_of_payment"),
]

royalty/users/urls.py
from django.urls import path

from royalty.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

event/models.py
from django.db import models



# Create your models here.

class PrivateEvent(models.Model):
    treated_user = models.CharField(max_length=155)
    point_of_contact = models.ForeignKey('users.User', on_delete=models.CASCADE)
    description = models.TextField()
    tier = models.IntegerField()
    estimated_amount = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        permissions = (
            ("cannot_view_private_event", "Cannot view private event"),
            ("can_edit_private_event", "Can edit private event"),
        )
    
    def __str__(self):
        return self.treated_user
    

class InviteEvent(models.Model):
    private_event = models.ForeignKey(PrivateEvent, on_delete=models.CASCADE)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    accepted = models.BooleanField(default=False)
    percentage_of_cost = models.IntegerField()
    event_amount = models.IntegerField()
    
    
    def __str__(self):
        return str(self.private_event) | str(self.email)

royalty/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for royalty.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

event/forms.py
from django import forms

from .models import PrivateEvent, InviteEvent

class PrivateEventForm(forms.ModelForm):
    class Meta:
        model = PrivateEvent
        fields = (
            'treated_user',
            'description',
            'tier',
            'estimated_amount',
            )
        
class InviteForm(forms.ModelForm):
   class Meta:
       model = InviteEvent
       fields = (
              'email',
              'phone_number',
              'percentage_of_cost',
              'event_amount',
              'accepted'
              )

royalty/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

event/views.py
from django.urls import reverse_lazy, reverse


from django.views.generic import ListView, CreateView, DetailView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import PrivateEvent, InviteEvent
from .forms import PrivateEventForm, InviteForm

# Create your views here.

class PrivateEventListView(LoginRequiredMixin, ListView):
    '''List all private events'''
    template_name = "events/private_event_list.html"
    model = PrivateEvent
    context_object_name = 'private_events'


    
class PrivateEventCreateView(LoginRequiredMixin, CreateView):
    '''Create a private event'''
    template_name = "events/private_event_add.html"
    model = PrivateEvent
    form_class = PrivateEventForm
    success_url = reverse_lazy('events:invite_private_event') #next html is invite_private_event.html
    
    def form_valid(self, form):
        form.instance.point_of_contact = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('events:invite_private_event', kwargs={'pk': self.object.pk})  #next html is invite_private_event.html

    
class PrivateEventInviteView(LoginRequiredMixin, CreateView):
    '''Create an invite to a private event'''
    template_name = "events/invite_private_event.html"
    model = InviteEvent  
    form_class = InviteForm
    success_url = reverse_lazy('events:private_event_detail')
    
    def form_valid(self, form):
        form.instance.point_of_contact = self.request.user
        form.instance.private_event = PrivateEvent.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['private_event'] = PrivateEvent.objects.get(pk=self.kwargs['pk'])
        return context
    
    def get_success_url(self):
        return reverse('events:private_event_detail', kwargs={'pk': self.object.private_event.pk})
    
class PrivateEventDetailView(LoginRequiredMixin,DetailView):
    model = PrivateEvent
    template_name = "events/private_event_detail.html"
    context_object_name = 'private_event' 

class MethodOfPaymentView(TemplateView):
    model = PrivateEvent
    template_name = "events/method_of_payment.html"
    context_object_name = 'private_event'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['private_event'] = PrivateEvent.objects.latest('created_at')
        return context

royalty/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

royalty/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

royalty/templates/events/invite_private_event.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Invite Private Event{% endblock title %}
{% block content %}
<h3>invite private event.html</h3>
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Send</button>
    <a href="{% url 'events:private_event_detail' private_event.id %}" class="btn btn-primary">Back</a>

</form>
    
{% endblock content %}

royalty/templates/events/method_of_payment.html
{% extends 'base.html' %}



{% block title %}Method of Payment{% endblock title %}
{% block content %}
<h3>method of payment</h3>
<p>Connect to strip for payment</p>

<a href="{% url 'events:private_event_detail' private_event.id %}">Back</a>

{% endblock content %}

royalty/templates/events/private_event_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Private Event Add{% endblock title %}

{% block content %}
<h3>private event add.html</h3>
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Invite Contributers</button>
</form>
{% endblock content %}

royalty/templates/events/private_event_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Private Event Detail{% endblock title %}
{% block content %}
<h3>private event detail.html</h3>
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Invite</button>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
<a href="{% url 'events:private_event_detail' private_event.id %}">View Event</a>
{% endblock content %}

royalty/templates/events/private_event_list.html
{% extends 'base.html' %}
{% block title %}Private Event List{% endblock title %}

{% block content %}
<h3>private event html</h3>
<!-- This page will list all private events and the option to add a new private event. -->


<a href="{% url 'events:private_event_add' %}" class="btn btn-primary">Add Private Event</a>
<a href="{% url 'home' %}" class="btn btn-primary">Back</a>


<p>List all events</p>
 {% for private_event in private_events %}
    <p>{{ private_event.name }}</p>
    <p>{{ private_event.date }}</p>
    <p>{{ private_event.time }}</p>
    <p>{{ private_event.location }}</p>
    <p>{{ private_event.description }}</p>
    <p>{{ private_event.method_of_payment }}</p>
    <p>{{ private_event.amount }}</p>

{% endfor %}

{% endblock content %}