event/urls.py
from django.urls import path
from .views import (
    PrivateEventListView, 
    PrivateEventCreateView, 
    PrivateEventInviteView, 
    PrivateEventDetailView,
    MethodOfPaymentView,
    )


app_name = "events"
urlpatterns = [
    path("", PrivateEventListView.as_view(), name="private_event_list"),
    path("new/", PrivateEventCreateView.as_view(), name="private_event_add"),
    path("<int:pk>/invite/", PrivateEventInviteView.as_view(), name="invite_private_event"),
    path("<int:pk>/", PrivateEventDetailView.as_view(), name="private_event_detail"),
    path("payment/", MethodOfPaymentView.as_view(), name="method_of_payment"),
]

goals/urls.py
from django.urls import path
from goals.views import GoalsAddView, GoalsUpdateView, GoalsDeleteView, GoalsListView

app_name = "goals"
urlpatterns = [
    path("", GoalsListView.as_view(), name="goals_list"),
    path("new/", GoalsAddView.as_view(), name="goals_add"),
    path("<int:pk>/", GoalsUpdateView.as_view(), name="goals_edit"),
    path("<int:pk>/delete/", GoalsDeleteView.as_view(), name="goals_delete"),
]

royalty/users/urls.py
from django.urls import path

from royalty.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

goals/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User


class Goals(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    once_a_month = models.CharField(max_length=255, blank=True)
    once_a_month_amount = models.IntegerField(blank=True)
    once_a_quarter = models.CharField(max_length=255, blank=True)
    once_a_quarter_amount = models.IntegerField(blank=True)
    once_a_year = models.CharField(max_length=255, blank=True)
    once_a_year_amount = models.IntegerField(blank=True)
    once_every_five_years = models.CharField(max_length=255, blank=True)
    once_every_five_years_amount = models.IntegerField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return str(self.created_at)
    
    def get_absolute_url(self):
        return reverse('goals_detail', kwargs={'pk': self.pk})

royalty/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for royalty.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

goals/forms.py
from django import forms

from .models import Goals

class GoalsForm(forms.ModelForm):
    class Meta:
        model = Goals
        fields = (
            'once_a_month',
            'once_a_month_amount',
            'once_a_quarter',
            'once_a_quarter_amount',
            'once_a_year', 
            'once_a_year_amount', 
            'once_every_five_years', 
            'once_every_five_years_amount',
            )
        widgets = {
            "once_a_month": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter what you want to do once a month",
                    "rows": 3,
                    }),
            "once_a_month_amount": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Approxiamate $ value",
                    "rows": 1,
                    }),
            "once_a_quarter": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter what you want to do once a quarter",
                    "rows": 3,
                    }),
            "once_a_quarter_amount": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Approxiamate $ value",
                    "rows": 1,
                    }),
            "once_a_year": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter what you want to do once a year",
                    "rows": 3,
                    }),
            "once_a_year_amount": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Approxiamate $ value",
                    "rows": 1,
                    }),
            "once_every_five_years": forms.Textarea(
                attrs={"class": "form-control",
                       "placeholder": "Enter what you want to do once every five years",
                       "rows": 3,
                    }),
            "once_every_five_years_amount": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Approxiamate $ value",
                    "rows": 1,
                    }),
        }

royalty/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

goals/views.py
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ImproperlyConfigured
from .models import Goals
from .forms import GoalsForm


class GoalsAddView(LoginRequiredMixin,CreateView):
    '''Add a new goal'''
    template_name = "goals/goals_add.html"
    model = Goals
    form_class = GoalsForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('home')

class GoalsListView(LoginRequiredMixin, ListView):
    '''List all goals'''
    model = Goals
    template_name = "goals/goals_list.html"
    context_object_name = 'goals'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Goals.objects.filter(user=self.request.user).order_by('-created_at')
        else:
            return Goals.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['goal'] = context['object_list'].first() if context['object_list'] else None
        return context
    


class GoalsUpdateView(LoginRequiredMixin, UpdateView):
    '''edit goals'''
    model = Goals
    template_name = "goals/goals_edit.html"
    fields = (
        'once_a_month',
        'once_a_month_amount',
        'once_a_quarter',
        'once_a_quarter_amount',
        'once_a_year',
        'once_a_year_amount',
        'once_every_five_years',
        'once_every_five_years_amount',
    )
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['goals'] = Goals.objects.get(pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse('goals:goals_list')
    
class GoalsDeleteView(LoginRequiredMixin, DeleteView):
    '''delete goals'''
    model = Goals
    template_name = "goals/goals_delete.html"
    context_object_name = 'goals'
    
    def get_success_url(self):
        return reverse('goals:goals_list')

    

royalty/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

royalty/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

royalty/templates/goals/goals.html
{% extends "base.html" %}
<!-- {% load crispy_forms_tags %} -->

{% block title %}Goals{% endblock title %}

{% block content %}
<div class="goals-header">
    <h3>Goals</h3>
    <p>Enter your goals and approxiate dollar value for each goal</p>
    <table class="goals-table">
        <tbody class="goals-body">
            <form method="post">
                {% csrf_token %}
                <div class="sub-goals">
                    <p>Enter your monthly rewards</p>
                    <div class="goal-text">
                    {{ form.once_a_month }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_a_month_amount }}
                    </div>
                </div>
                <div class="sub-goals">
                    <p>Enter your quarterly rewards</p>
                    <div class="goal-text">
                    {{ form.once_a_quarter }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_a_quarter_amount }}
                    </div>
                </div>
                <div class="sub-goals">
                    <p>Enter your annual reward</p>
                    <div class="goal-text">
                    {{ form.once_a_year }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_a_year_amount }}
                    </div>
                </div>
                <div class="sub-goals">
                    <p>Enter your reward that you would do every 5 years</p>
                    <div class="goal-text">
                    {{ form.once_every_five_years }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_every_five_years_amount }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </tbody>
    </table>
</div> 

{% endblock content %}

royalty/templates/goals/goals_add.html
{% extends "base.html" %}
<!-- {% load crispy_forms_tags %} -->

{% block title %}Goals{% endblock title %}

{% block content %}
<h2>goals_add.html</h2>
<div class="goals-header">
    <h3>Goals</h3>
    <p>Enter your goals and approxiate dollar value for each goal</p>
    <table class="goals-table">
        <tbody class="goals-body">
            <form method="post">
                {% csrf_token %}
                <div class="sub-goals">
                    <p>Enter your monthly rewards</p>
                    <div class="goal-text">
                    {{ form.once_a_month }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_a_month_amount }}
                    </div>
                </div>
                <div class="sub-goals">
                    <p>Enter your quarterly rewards</p>
                    <div class="goal-text">
                    {{ form.once_a_quarter }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_a_quarter_amount }}
                    </div>
                </div>
                <div class="sub-goals">
                    <p>Enter your annual reward</p>
                    <div class="goal-text">
                    {{ form.once_a_year }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_a_year_amount }}
                    </div>
                </div>
                <div class="sub-goals">
                    <p>Enter your reward that you would do every 5 years</p>
                    <div class="goal-text">
                    {{ form.once_every_five_years }}
                    </div>
                    <div class="goal-amount">
                    {{ form.once_every_five_years_amount }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </tbody>
    </table>
</div> 

{% endblock content %}

royalty/templates/goals/goals_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Delete Goal</h2>
  <p>Are you sure you want to delete this goal?</p>

  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm">
  </form>

  <a href="{% url 'goals:goals' %}">Cancel</a>
{% endblock content %}

royalty/templates/goals/goals_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Goal Detail{% endblock title %}

{% block content %}
<h2>goals_edit.html</h2>
<div class="goals-header">
    <h3>Goal Detail</h3>
    <table class="goals-table">
        <tbody class="goals-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
            <!-- <div class="sub-goals">
                <p>Once a month: {{ goals.once_a_month }}</p>
                <p>Once a month amount: {{ goals.once_a_month_amount }}</p>
            </div>
            <div class="sub-goals">
                <p>Once a quarter: {{ goals.once_a_quarter }}</p>
                <p>Once a quarter amount: {{ goals.once_a_quarter_amount }}</p>
            </div>
            <div class="sub-goals">
                <p>Once a year: {{ goals.once_a_year }}</p>
                <p>Once a year amount: {{ goals.once_a_year_amount }}</p>
            </div>
            <div class="sub-goals">
                <p>Once every five years: {{ goals.once_every_five_years }}</p>
                <p>Once every five years amount: {{ goals.once_every_five_years_amount }}</p>
            </div> -->
            
        </tbody>
    </table>
</div> 
{% endblock content %}

royalty/templates/goals/goals_list.html
{% extends "base.html" %}

{% block title %}Goal List{% endblock title %}

{% block content %}
<h2>goals_list.html</h2>
<h2>Here are you goals</h2>
{% if goal %}

<div class="goals-header">
    <h3>Goal Detail</h3>
    <table class="goals-table">
        <tbody class="goals-body">
            <div class="sub-goals">
                <p>Once a month: {{ goal.once_a_month }}</p>
                <p>Once a month amount: {{ goal.once_a_month_amount }}</p>
            </div>
            <div class="sub-goals">
                <p>Once a quarter: {{ goal.once_a_quarter }}</p>
                <p>Once a quarter amount: {{ goal.once_a_quarter_amount }}</p>
            </div>
            <div class="sub-goals">
                <p>Once a year: {{ goal.once_a_year }}</p>
                <p>Once a year amount: {{ goal.once_a_year_amount }}</p>
            </div>
            <div class="sub-goals">
                <p>Once every five years: {{ goal.once_every_five_years }}</p>
                <p>Once every five years amount: {{ goal.once_every_five_years_amount }}</p>
            </div>
            <a href="{% url 'goals:goals_edit' goal.pk %}" class="btn btn-primary">Edit</a>
        </tbody>
    </table>
</div> 
{% else %}
    <p>No goals to display.</p>
{% endif %}

{% endblock content %}