event/urls.py
from django.urls import path
from .views import (
    PrivateEventListView, 
    PrivateEventCreateView, 
    PrivateEventInviteView, 
    PrivateEventDetailView,
    MethodOfPaymentView,
    )


app_name = "events"
urlpatterns = [
    path("", PrivateEventListView.as_view(), name="private_event_list"),
    path("new/", PrivateEventCreateView.as_view(), name="private_event_add"),
    path("<int:pk>/invite/", PrivateEventInviteView.as_view(), name="invite_private_event"),
    path("<int:pk>/", PrivateEventDetailView.as_view(), name="private_event_detail"),
    path("payment/", MethodOfPaymentView.as_view(), name="method_of_payment"),
]

royalty/users/urls.py
from django.urls import path

from royalty.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tools/urls.py
from django.urls import path
from tools.views import (
    ToolsListView,
    ToolsDashboardView, 
    WillpowerToolView,
    WillpowerDetailView,
    FlowToolView,
    FlowDetailView,
    PressureToolView,
    PressureDetailView,
    OneThingToolView,
    OneThingDetailView,

)

app_name = "tools"
urlpatterns = [
    path("", ToolsListView.as_view(), name="tools_list"),
    path("willpower/", WillpowerToolView.as_view(), name="willpower"),
    path("willpower/<int:pk>/", WillpowerDetailView.as_view(), name="willpower_detail"),
    path("flow/", FlowToolView.as_view(), name="flow"),
    path("flow/<int:pk>/", FlowDetailView.as_view(), name="flow_detail"),
    path("pressure/", PressureToolView.as_view(), name="pressure"),
    path("pressure/<int:pk>/", PressureDetailView.as_view(), name="pressure_detail"),
    path("onething/", OneThingToolView.as_view(), name="one_thing"),
    path("onething/<int:pk>/", OneThingDetailView.as_view(), name="one_thing_detail"),
    path("dashboard/", ToolsDashboardView.as_view(), name="tools_dashboard"),
]

    

royalty/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for royalty.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

tools/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date

class WillpowerTool(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    willpower_rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    description = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return str(self.created_at) + " " + str(self.willpower_rating) + " " + str(self.description)
    
    def get_absolute_url(self):
        return reverse('tools_detail', kwargs={'pk': self.pk})
    
class FlowTool(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    flow_rating = models.IntegerField(default=0, choices=[(i, i) for i in range(-2, 3)])
    description = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.created_at) | (self.flow_rating) | str(self.name)

class PressureTool(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    now_pressure_release = models.BooleanField(default=False)
    now_release_description = models.CharField(max_length=255, blank=True)
    later_pressure_release = models.BooleanField(default=False)
    later_release_time = models.DateTimeField()
    later_release_description = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.created_at) | (self.now_pressure_release) | (self.later_pressure_release) | str(self.name)
    
class OneThingTool(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    one_thing_description = models.CharField(max_length=255, blank=True)
    one_thing_time = models.DateField(default=date.today, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.created_at) | (self.one_thing_description) | str(self.name)
 
class ToolsList(models.Model):
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.created_at) | str(self.name)

royalty/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

tools/forms.py
from django import forms
from .models import WillpowerTool, FlowTool, PressureTool, OneThingTool


class WillpowerToolForm(forms.ModelForm):
    class Meta:
        model = WillpowerTool
        fields = ('willpower_rating', 'description',)

        widgets = {"description": forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Enter willpower driver here",
                "rows": 1,
                })}

class FlowToolForm(forms.ModelForm):
    class Meta:
        model = FlowTool
        fields = ('flow_rating', 'description',)

        widgets = {"description": forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Enter your trigger here",
                "rows": 1,
                })}


class PressureToolForm(forms.ModelForm):
    class Meta:
        model = PressureTool
        fields = (
            'now_pressure_release', 
            'later_pressure_release', 
            )

class PressureNowForm(forms.ModelForm):
    class Meta:
        model = PressureTool
        fields = (
            'now_release_description', 
            )

class PressureLaterForm(forms.ModelForm):
    class Meta:
        model = PressureTool
        fields = (
            'later_release_time',
            'later_release_description', 
            ) 

        
class OneThingToolForm(forms.ModelForm):
    class Meta:
        model = OneThingTool
        fields = ('one_thing_description', 'one_thing_time',)
    

royalty/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

royalty/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tools/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import UpdateView, ListView, TemplateView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import WillpowerTool, FlowTool, PressureTool, OneThingTool, ToolsList
from .forms import WillpowerToolForm, FlowToolForm, PressureToolForm, OneThingToolForm, PressureNowForm, PressureLaterForm

# Create your views here.

class ToolsListView(ListView):
    model = ToolsList 
    template_name = 'tools/tools_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Welcome to the home page!'
        return context


class WillpowerToolView(LoginRequiredMixin, CreateView):
    model = WillpowerTool
    form_class = WillpowerToolForm
    template_name = 'tools/willpower.html'
    success_url = reverse_lazy('tools:willpower')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['water_level'] = int(self.request.POST.get('rating', 0)) * 20
        else:
            context['water_level'] = 0  # Default value
        
        # add willpower tools to context
        context['willpowers'] = WillpowerTool.objects.filter(user=self.request.user)

        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



class WillpowerDetailView(LoginRequiredMixin,DetailView):
    model = WillpowerTool
    form_class = WillpowerToolForm
    template_name = 'tools/willpower_detail.html'
    


class FlowToolView(LoginRequiredMixin, CreateView):
    model = FlowTool
    form_class = FlowToolForm
    template_name = 'tools/flow.html'
    success_url = reverse_lazy('tools:flow')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class FlowDetailView(LoginRequiredMixin, UpdateView):
    model = FlowTool
    form_class = FlowToolForm
    template_name = 'tools/flow_detail.html'
    
    

class PressureToolView(LoginRequiredMixin, TemplateView):
    template_name = 'tools/pressure_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now_form'] = PressureNowForm(self.request.POST or None)
        context['later_form'] = PressureLaterForm(self.request.POST or None)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        now_form = context['now_form']
        later_form = context['later_form']
        if now_form.is_valid():
            now_form.save()
        elif later_form.is_valid():
            later_form.save()
        return self.render_to_response(context)
    
class PressureDetailView(LoginRequiredMixin, UpdateView):
    model = PressureTool
    form_class = PressureToolForm
    template_name = 'tools/pressure_detail.html'


class OneThingToolView(LoginRequiredMixin,CreateView):
    model = OneThingTool
    form_class = OneThingToolForm
    template_name = 'tools/one_thing.html'
    success_url = reverse_lazy('tools:tools_list')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class OneThingDetailView(LoginRequiredMixin, UpdateView):
    model = OneThingTool
    form_class = OneThingToolForm
    template_name = 'tools/one_thing_detail.html'

class ToolsDashboardView(ListView):
    model = WillpowerTool, FlowTool, PressureTool, OneThingTool
    template_name = 'tools/tools_dashboard.html'
    context_object_name = 'tools_dashboard'

royalty/templates/tools/flow.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Tool List{% endblock title %}
{% block content %}
<h3>flow.html</h3>

<div class="flow-card">
    <form class="flow-form" method="post" action="">
        <div class="flow-chart-container">
            <canvas id="flowChart"></canvas>
            <div class="flow-slider-container">
                <input class="flow-slider" type="range" min="-2" max="2" value="{{ form.instance.flow_rating }}" id="myRange">
            </div>
        </div>
        {% csrf_token %}
        <div class="flow-text">
            <div>Enter Reason</div>
            {{ form.description }}
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>


<!-- here is the javascript for the flow chart -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
document.addEventListener("DOMContentLoaded", function () {
    var dropdown = document.querySelector(".flow-slider");
    var ctx = document.getElementById('flowChart').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: ['Flow'],
            datasets: [{
                label: 'Flow',
                data: [dropdown.value, 5 - dropdown.value],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
            rotation: 0 // Initial rotation
        }
    });
    function updateChart(value) {
        var percentage, rotation;
        switch (value) {
            case "-2":
                percentage = 5;
                rotation = Math.PI * 57; // 180 degrees
                break;
            case "-1":
                percentage = 1.7;
                rotation = Math.PI * 57; // 180 degrees
                break;
            case "0":
                percentage = 0;
                break;
            case "1":
                percentage = 1.7;
                rotation = Math.PI * 29; // 180 degrees
                break;
            case "2":
                percentage = 5;
                break;
        }
        
        
        chart.data.datasets[0].data[0] = percentage;
        chart.options.rotation = rotation; // Update rotation
        chart.update();
    }

    dropdown.onchange = function () {
        updateChart(this.value);
    }
    // Initial update
    updateChart(dropdown.value);
});
</script>

{% endblock content %}
```

royalty/templates/tools/flow_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Flow Detail{% endblock title %}

{% block content %}
<h2>flow_detail.html</h2>
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>

{% endblock content %}

royalty/templates/tools/one_thing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}One Thing{% endblock title %}
{% block content %}
<h3>onething.html</h3>

<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock content %}

royalty/templates/tools/one_thing_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}One Thing Detail{% endblock title %}

{% block content %}
<h2>onething_detail.html</h2>
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>

{% endblock content %}

royalty/templates/tools/pressure.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Pressure{% endblock title %}

{% block content %}
<h2>pressure.html</h2>

<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
    
{% endblock content %}

royalty/templates/tools/pressure_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Pressure detail{% endblock title %}

{% block content %}
<h2>pressure_detail.html</h2>
<div class="pressure-buttons">
    <button type="button" class="btn btn-primary" id="breakNowButton">Break Now</button>
    <button type="button" class="btn btn-primary" id="scheduleBreakButton">Schedule Break</button>
</div>

<form method="post" action="" id="pressureNowForm" style="display: none;">
    {% csrf_token %}
    {{ now_form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<form method="post" action="" id="pressureLaterForm" style="display: none;">
    {% csrf_token %}
    {{ later_form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<script>
    document.getElementById('breakNowButton').addEventListener('click', function() {
        document.getElementById('pressureNowForm').style.display = 'block';
        document.getElementById('pressureLaterForm').style.display = 'none';
    });

    document.getElementById('scheduleBreakButton').addEventListener('click', function() {
        document.getElementById('pressureLaterForm').style.display = 'block';
        document.getElementById('pressureNowForm').style.display = 'none';
    });
</script>

{% endblock content %}

royalty/templates/tools/tools_dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<h2>tools_dashboard.html</h2>

{% endblock content %}

royalty/templates/tools/tools_list.html
{% extends 'base.html' %}

{% block title %}Tool List{% endblock title %}


{% block content %}
<h3>tools_list.html</h3>

<table>
    <div class="card">
        <a href="{% url 'tools:willpower' %}">
            <h3>Willpower</h3>
        </a>
            <p>Willpower is the ability to resist short-term temptations in order to meet long-term goals.</p>
    </div>
    <div class="card">
        <a href="{% url 'tools:flow' %}">
            <h3>Mental Flow</h3>
        </a>
            <p>Flow is the mental sweet spot between challenge and ease. 
                Work in the flow state should feel engaging. 
            </p>
        
    </div>
    <div class="card">
        <a href="{% url 'tools:pressure' %}">
            <h3>Pressure</h3>
        </a>
            <p>When you need a break? And how do you unplug?</p>
        
    </div>
    <div class="card">
        <a href="{% url 'tools:one_thing' %}">
            <h3>One Thing</h3>
        </a>
            <p>What one thing, if accomplished today, would make today successful?</p>
        
    </div>
</table>

{% endblock content %}

royalty/templates/tools/willpower.html
{% extends "base.html" %}
{% load static %}

{% block title %}Willpower Detail{% endblock title %}

{% block content %}
<h2>Willpower</h2>
<h2>Rate the Water Level</h2>



<div class="willpower-card">
    <form class="willpower-form" method="post" action="">
        <div class="willpower-chart-container">
            <canvas id="myChart"></canvas>
            <div class="slider-container">
                <input class="slider" type="range" min="1" max="5" value="{{ form.instance.willpower_rating }}" id="myRange">
            </div>
        </div>
        {% csrf_token %}
        <div class="willpower-text">
            <div>Enter Reason</div>
            {{ form.description }}
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>


<div class="willpower-recap">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Reason</th>
                <th scope="col">Willpower Rating</th>
                <th scope="col">Date</th>
            </tr>
        </thead>
        <tbody>
            {% for willpower in willpowers %}
            <tr>
                <td>{{ willpower.description }}</td>
                <td>{{ willpower.willpower_rating }}</td>
                <td>{{ willpower.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var slider = document.getElementById("myRange");
        var ctx = document.getElementById('myChart').getContext('2d');
        var chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ["Willpower"],
                datasets: [{
                    label: "Willpower",
                    data: [slider.value],
                    backgroundColor: 'rgba(0, 123, 255, 0.5)',
                    borderColor: 'rgba(0, 123, 255, 1)',
                    borderWidth: 1,
                    borderRsdius: 10
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 5,
                        ticks: {
                            stepSize: 1
                        }
                    }
                }
            }
        });

        slider.oninput = function() {
            console.log('Slider value:', this.value);  // Log slider value
            chart.data.datasets[0].data[0] = this.value;
            chart.update();
            console.log('Dataset data:', chart.data.datasets[0].data);  // Log dataset data
        }
    });
    // var slider = document.getElementById("myRange");
    // var ctx = document.getElementById('myChart').getContext('2d');
    // var chart = new Chart(ctx, {
    //     type: 'bar',
    //     data: {
    //         labels: ["Willpower"],
    //         datasets: [{
    //             label: "Willpower Rating",
    //             data: [slider.value],
    //             backgroundColor: 'rgba(0, 123, 255, 0.5)',
    //             borderColor: 'rgba(0, 123, 255, 1)',
    //             borderWidth: 1,
    //             borderRsdius: 10
    //         }]
    //     },
    //     options: {
    //         responsive: true,
    //         maintainAspectRatio: true,
    //         scales: {
    //             y: {
    //                 beginAtZero: true,
    //                 max: 5,
    //                 ticks: {
    //                     stepSize: 1
    //                 }
    //             }
    //         }
    //     }
    // });

    // slider.oninput = function() {
    //     console.log('Slider value:', this.value);  // Log slider value
    //     chart.data.datasets[0].data[0] = this.value;
    //     chart.update();
    //     console.log('Dataset data:', chart.data.datasets[0].data);  // Log dataset data
    // }
    
</script>
{% endblock content %}
    ```

royalty/templates/tools/willpower_detail.html
<!-- {% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Willpower List{% endblock title %}

{% block content %}
<h2>willpower_list.html</h2>
<form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>

{% endblock content %} -->